### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by mikedao** [HoffsMH/dad_jokes_for_days#50]
Title: 

As a visitor
When I visit "/"
Then I should see a link for "Login"
And when I click link "Create Account"
Then my current page should be "/dashboard"
And I should see a message in the navbar that says "Logged in as SOME_USER"
And I should see my profile information
And I should not see a link for "Login"
And I should see a link for "Logout"

When I click "Logout"
Then I should see see "Login"
And I should not see "Logout"

**Comment by MowAlon** [comment]
This workflow doesn't actually make sense, so we'll have to adjust it. This suggests that a user would see the message "Logged in as <user>" without having created an account or logged in... so we're working under the assumption that you want the user to go through the login process before being logged in or seeing the successful login announcement.
