### ISSUE TITLE
Admin Orders

### ISSUE THREAD

**Issue by mikedao** [HoffsMH/dad_jokes_for_days#96]
Title: Admin Orders

As an Admin
When I visit the dashboard
Then I can see a listing of all orders
And I can see the total number of orders for each status ("Ordered", "Paid", "Cancelled", "Completed")
And I can see a link for each individual order
And I can filter orders to display by each status type  ("Ordered", "Paid", "Cancelled", "Completed")
And I have links to transition the status
  - I can click on "cancel" on individual orders which are "paid" or "ordered"
  - I can click on "mark as paid" on orders that are "ordered"
  - I can click on "mark as completed" on orders that are "paid"

**Comment by MowAlon** [comment]
So many questions...

**Comment by MowAlon** [comment]
After talking to product owner, Dao, learned that the admin should be able to revert to any status due to possible mistaken clicking. Opting for the ability to switch to any status from any status rather than filtering status links based on current status.

**Comment by MowAlon** [comment]
Still working on links to each individual order
and
filtering to show only orders of a single status
